name: lemon_engine_example
description: An example for the lemon engine

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  lemon_engine: ^0.3.29

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - images/
  uses-material-design: true
